edmundhung/conform

examples/remix/app/routes/material-ui.tsx, examples/remix/app/routes/order.tsx, examples/remix/app/routes/search.tsx, packages/conform-dom/index.ts, packages/conform-react/README.md, packages/conform-react/helpers.ts, packages/conform-react/hooks.ts
This is to align the naming with the DOM element's `defaultValue`.
=> feat(conform-dom,conform-react)!: rename initialValue to defaultValue

examples/remote/README.md, examples/remote/src/App.tsx, packages/conform-dom/README.md, tests/helpers.ts
Time to release a new version 🎉
=> chore: docs update

packages/conform-react/README.md
=> doc: fix typo

packages/conform-react/README.md
Seems like this might be a typo.
=> Change `book` to `isbn`

examples/list/src/App.tsx, examples/remix/app/entry.server.tsx, examples/remix/app/root.tsx, examples/remix/app/routes/index.tsx, examples/remix/sandbox.config.json, guide/app/components.tsx
There are always something you missed when you try to ship something asap 😅
=> doc: website updates

examples/material-ui/src/App.tsx, packages/conform-react/README.md, packages/conform-react/helpers.ts, packages/conform-react/hooks.ts, playground/app/routes/basic.tsx, tests/basic.spec.ts, tests/helpers.ts
This PR enables auto focus for first invalid field in the form including controlled input, together with update on the `conform` helper to utilise the `autoFocus` attributes on no-js environment.
No breaking changes.
=> feat(conform-react):  error autofocus support

examples/advanced/README.md
I the button value example, it's not clear where the button value is until you look at the Codesandbox, so this commit adds an inline comment in the HTML example.
=> Add comment about button values

.github/workflows/tests.yml
To avoid confusion, new changes will only be merged to `dev` branch. The `main` branch would be reserved for the latest release.
=> chore: run ci on dev pull request

docs/tutorial.md, docs/validation.md, examples/remix-async-validation/app/routes/index.tsx, examples/remix-nested-list/app/routes/index.tsx, examples/remix/README.md, examples/remix/app/routes/index.tsx, examples/yup/app/routes/index.tsx, examples/zod/app/routes/index.tsx, packages/conform-react/README.md, packages/conform-react/hooks.ts, playground/app/components.tsx, playground/app/routes/async-validation.tsx, playground/app/routes/file-upload.tsx, playground/app/routes/input-attributes.tsx, playground/app/routes/login.tsx, playground/app/routes/movie.tsx, playground/app/routes/multiple-errors.tsx, playground/app/routes/payment.tsx, playground/app/routes/radio-buttons.tsx, playground/app/routes/signup.tsx, playground/app/routes/simple-list.tsx, playground/app/routes/todos.tsx, playground/app/routes/validate-constraint.tsx, playground/app/routes/validate.tsx
I don't know why I named it state before. Let's make it clear.
=> feat(conform-react)!: rename state to lastSubmission

packages/conform-react/hooks.ts, playground/app/components.tsx, playground/app/routes/reset-default-value.tsx, tests/integrations/reset-default-value.spec.ts
=> fix(conform-react): defaultValue should not be cached

examples/react-router/src/signup.tsx, examples/react-router/src/todos.tsx, examples/remix/app/routes/login.tsx, examples/remix/app/routes/signup.tsx, examples/remix/app/routes/todos.tsx, packages/conform-dom/index.ts, packages/conform-dom/parse.ts, packages/conform-dom/types.ts, packages/conform-react/hooks.ts, packages/conform-zod/index.ts, playground/app/routes/reset-default-value.tsx, playground/app/routes/signup.tsx, playground/app/routes/todos.tsx, tests/conform-yup.spec.ts, tests/conform-zod.spec.ts, tests/integrations/multiple-errors.spec.ts, tests/integrations/radio-buttons.spec.ts, tests/integrations/simple-list.spec.ts, tests/integrations/validate.spec.ts, tests/react.spec.ts
Made some minor adjustment on the `Submission` type and improved type inference capability on the `useForm` hook.
=> feat(conform-react,conform-zod): better type inference

packages/conform-dom/types.ts, packages/conform-react/helpers.ts, packages/conform-react/hooks.ts, playground/app/routes/simple-list.tsx
=> fix(conform-react): fieldset & fieldlist type inference with undefined / unknown

.gitignore, package-lock.json, package.json, packages/conform-dom/package.json, packages/conform-react/package.json, packages/conform-validitystate/package.json, packages/conform-yup/package.json, packages/conform-zod/package.json, rollup.config.js
fix https://github.com/epicweb-dev/epic-stack/issues/98
=> build: refine esm setup

packages/conform-dom/formdata.ts, packages/conform-dom/index.ts, packages/conform-dom/intent.ts, packages/conform-dom/parse.ts, tests/conform-dom.spec.ts
=> fix(conform-dom): ignore duplicated intent

packages/conform-dom/intent.ts, tests/conform-dom.spec.ts
=> fix: parsing intent with extra slash

packages/conform-react/helpers.ts, tests/conform-react.spec.ts
Fix #186 with tests to avoid regression 😓
=> fix(conform-react): invalid hidden style property

.eslintrc.json, packages/conform-react/hooks.ts
I should explicitly disable the rule if the console call is needed.
=> chore: disallow console unless intentional

examples/react-router/src/todos.tsx, examples/remix/app/routes/todos.tsx, guide/app/root.tsx, packages/conform-yup/README.md, packages/conform-zod/README.md, playground/app/routes/async-validation.tsx, playground/app/routes/custom-inputs.tsx, playground/app/routes/form-attributes.tsx, playground/app/routes/index.tsx, playground/app/routes/login.tsx, playground/app/routes/movie.tsx, playground/app/routes/payment.tsx, playground/app/routes/reset-default-value.tsx, playground/app/routes/signup.tsx, playground/app/routes/todos.tsx
just doing some house keeping before I start digging into ID stuff
=> chore: cleanup playground code

packages/conform-react/hooks.ts, playground/app/routes/simple-list.tsx, tests/integrations/simple-list.spec.ts
Fixed an issue with list default value restored after deletion.
=> fix(conform-react): default value should not be restored once delete

.github/workflows/tests.yml
Ensure all test suites ran before releasing a new version.
=> chore: run ci on next branch

docs/file-upload.md
Your PR was merged and the bug was fixed. Hooray! Thanks!
=> docs: remove outdated note about remix

docs/accessibility.md, docs/integrations.md, packages/conform-react/README.md, packages/conform-react/helpers.ts, playground/app/routes/input-attributes.tsx, tests/conform-react.spec.ts
=> feat(conform-react)!: default aria attributes to true

packages/conform-zod/coercion.ts, tests/conform-zod.spec.ts
=> fix(conform-zod): type coercion with optional schema

README.md, docs/complex-structures.md, docs/intent-button.md, docs/tutorial.md, docs/validation.md, examples/react-router/src/signup.tsx, examples/react-router/src/todos.tsx, examples/remix/app/routes/signup.tsx, examples/remix/app/routes/todos.tsx, examples/zod/app/routes/index.tsx, packages/conform-zod/README.md, packages/conform-zod/coercion.ts, packages/conform-zod/parse.ts, playground/app/routes/async-validation.tsx, playground/app/routes/validation-flow.tsx, tests/integrations/validation-flow.spec.ts
Now that we have auto type coercion with zod, it's time to update the docs to reflect it.
=> docs: update zod instructions

docs/complex-structures.md
This is just a suggestion. I find calling props anything other than "props" is unnecessarily confusing to folks.
=> docs: use config prop

packages/conform-zod/parse.ts
=> fix: add params to refine

docs/complex-structures.md
* add missing import
* define missing variables
=> docs(complex-structures): improve nested array example

README.md
According to the remix docs, `useActionData` comes from `@remix-run/react` https://remix.run/docs/en/main/hooks/use-action-data
=> docs: Update README code example

docs/validation.md, packages/conform-zod/coercion.ts, tests/conform-zod.spec.ts
=> fix(conform-zod): do not coerce whitespace to 0

docs/api/zod/parseWithZod.md
=> docs: Describe Zod default

packages/conform-zod/coercion.ts, tests/conform-zod.spec.ts
=> Add support for z.catch coercion

docs/tutorial.md
Updated imports using the ones coming from the newest APIs, (remix and conform)
- Replace `ActionArgs` with `ActionFunctionArgs`
- Fixed tutorial function imports
=> docs: update tutorial.md with latest api changes

docs/tutorial.md, docs/upgrading-v1.md
this should fix the issue #412
=> docs: Update parse function to parseWithZod

docs/integration/nextjs.md
=> fix(docs): typo in `nextjs.md`

docs/validation.md
=> fixing small typos validation.md

docs/tutorial.md
Fix use of sendMessage in `action()`. `submission.value` should be used instead of `result.data` and `action()` should end with `redirect()` like initial example.
=> docs: Update tutorial.md

packages/conform-dom/form.ts, packages/conform-dom/index.ts, packages/conform-react/context.tsx, playground/app/components.tsx, playground/app/routes/typing.tsx
=> fix: nested discriminated union should be supported

packages/conform-dom/form.ts
=> fix(conform-dom): restrict proxy key to be string

guide/app/components.tsx
=> chore(conform-guide): show triangle on the summary with pointer as hint

docs/intent-button.md
I fixed that the index was not written in intent-button.md.
=> docs: Fix missing map index in intent-button.md

packages/conform-dom/form.ts, packages/conform-dom/submission.ts, playground/app/routes/recursive-list.tsx, tests/integrations/recursive-list.spec.ts
=> fix: conform should derive keys of nested list properly

packages/conform-dom/form.ts, playground/app/routes/form-control.tsx, tests/integrations/form-control.spec.ts
=> fix: update form value at the form level

packages/conform-dom/form.ts, packages/conform-dom/submission.ts, playground/app/routes/nested-list.tsx, tests/integrations/nested-list.spec.ts
Fix #493.
The recursive tests added on #528 isn't enough so I copied the example provided on #493 this time.
=> fix: ensure nested list keys to be generated properly

packages/conform-dom/form.ts, packages/conform-react/context.tsx
This makes Conform to report the submission result before the server result is returned.
=> feat: report submission on submit

packages/conform-dom/submission.ts
=> fix: getButtonProps types

packages/conform-dom/form.ts, playground/app/components.tsx, playground/app/routes/collection.tsx, tests/integrations/collection.spec.ts
=> fix: subfield errors should be consider validated based on its parent

packages/conform-dom/formdata.ts
=> fix: setValue should work with null

packages/conform-dom/form.ts, playground/app/routes/form-control.tsx, tests/integrations/form-control.spec.ts
=> fix: root key should be updated after form update

playground/package.json
Fix CI issue like [this one](https://github.com/edmundhung/conform/actions/runs/8870134624/job/24351588484).
=> chore(playground): ensure css is built before remix build

docs/integration/remix.md
=> docs: tips for form reset with default value from loader

.changeset/tender-kiwis-flash.md, packages/conform-zod/coercion.ts, tests/conform-zod.spec.ts
=> fix(conform-zod): enable zod object coercion

.github/workflows/release.yml, package.json
Hopefully this should fix https://github.com/edmundhung/conform/actions/runs/10801230716/job/29960954846#step:7:24
=> chore: fix workflow error with too many arguments passed to changesets

docs/ja/complex-structures.md
as you read document, schema key is not same as you get fields of task.
=> fix: fix document written about complex structure in japanese

docs/api/react/useForm.md, packages/conform-dom/form.ts
Thank you for such a nice library. I really like it.
I fixed some typos that I found in the document and comment.
=> docs: fix typo

.changeset/early-buckets-complain.md, packages/conform-zod/coercion.ts, tests/conform-zod.spec.ts
=> Fix type coercion for branded types

docs/ja/tutorial.md
fixed property names for japanese version
=> Update tutorial.md - Japanese version

.changeset/rich-masks-hang.md, packages/conform-zod/coercion.ts, tests/conform-zod.spec.ts
Pull Request for #892.
Thank you for your checking.
=> feat: Set empty object when zodDiscriminatedUnion is specified.

docs/api/valibot/coerceFormValue.md, docs/api/zod/coerceFormValue.md, docs/ja/api/valibot/coerceFormValue.md, docs/ja/api/zod/coerceFormValue.md
Hi,
Thank you for this package !!
just a small fix in the doc with the `disableAutoCoercion` option for the `parseWithZod`, `parseWithValibot` functions
=> doc: fix parseWithZod, parseWithValibot disableAutoCoercion

docs/installation.md, docs/ja/installation.md, guide/app/layout.tsx
Added documentation on installation for using Conform.
- To use Conform, you need to install the corresponding schema library and helper, so we have added detailed information.
- Since documentation for [using Zod v4](https://github.com/edmundhung/conform/pull/902#issuecomment-2816810238) will also be needed in the future, we are creating a new page.
=> docs: Add installation guide

packages/conform-valibot/package.json, pnpm-lock.yaml
https://github.com/edmundhung/conform/pull/929
I missed this in my review.
=> fix(conform-valibot): fix synchronize reference versions

.changeset/moody-rivers-build.md, packages/conform-react/integrations.ts, playground/app/routes/custom-inputs.tsx, tests/integrations/custom-inputs.spec.ts
=> fix: the value from useInputControl should be an array only if the element is a multiple select

.changeset/fast-buttons-love.md, packages/conform-dom/formdata.ts, packages/conform-dom/index.ts, packages/conform-react/future/util.ts, packages/conform-react/tests/useControl.node.test.tsx
=> fix(conform-react): ensure useControl works when File or FileList is undefined

.changeset/weak-carrots-eat.md, docs/api/react/future/isDirty.md, docs/api/react/future/useControl.md, docs/api/react/future/useFormData.md, docs/api/react/useForm.md, docs/ja/api/react/future/isDirty.md, docs/ja/api/react/future/useControl.md, docs/ja/api/react/future/useFormData.md, guide/app/layout.tsx, packages/conform-dom/dom.ts, packages/conform-dom/formdata.ts, packages/conform-dom/index.ts, packages/conform-dom/tests/dom.browser.test.ts, packages/conform-dom/tests/formdata.browser.test.ts, packages/conform-react/future/context.tsx, packages/conform-react/future/hooks.tsx, packages/conform-react/future/index.ts, packages/conform-react/future/util.ts, packages/conform-react/tests/helpers.tsx, packages/conform-react/tests/useControl.node.test.tsx, packages/conform-react/tests/useFormData.browser.test.tsx, packages/conform-react/tests/useFormData.node.test.tsx
=> feat: introduce `useFormData` hook and `isDirty` helper

.changeset/violet-vans-cross.md, docs/api/react/future/useControl.md, docs/ja/api/react/future/useControl.md, packages/conform-dom/dom.ts, packages/conform-react/future/hooks.tsx, packages/conform-react/future/index.ts, packages/conform-react/tests/useControl.browser.test.tsx
Fix https://github.com/edmundhung/conform/discussions/975
=> fix: future useControl should reset file input if received an empty array

examples/headless-ui/package.json, examples/radix-ui/package.json, examples/shadcn-ui/package.json, pnpm-lock.yaml
- https://stackblitz.com/github/edmundhung/conform/tree/fix-example-on-stackbltiz/examples/headless-ui
- https://stackblitz.com/github/edmundhung/conform/tree/fix-example-on-stackbltiz/examples/shadcn-ui
- https://stackblitz.com/github/edmundhung/conform/tree/fix-example-on-stackbltiz/examples/radix-ui
=> chore: missing dependency on some examples

.changeset/spicy-walls-rhyme.md, packages/conform-zod/v3/tests/constraint.test.ts, packages/conform-zod/v4/constraint.ts, packages/conform-zod/v4/tests/constraint.test.ts
Pull Request for #997 
I also added tests for methods that return ZodPipe other than `transform`.
Thank you for your checking.
=> fix(conform-zod/v4): getZodConstraint should resolve ZodPipe similar to v3

.changeset/angry-coats-behave.md, examples/react-router/app/routes.ts, examples/react-router/app/routes/file-upload.tsx, examples/react-router/app/routes/signup.tsx, packages/conform-dom/dom.ts, packages/conform-dom/formdata.ts, packages/conform-dom/tests/dom.browser.test.ts, packages/conform-dom/tests/formdata.test.ts, packages/conform-dom/types.ts, packages/conform-react/future/hooks.tsx, packages/conform-react/future/intent.ts, packages/conform-react/future/state.ts, packages/conform-react/future/types.ts, packages/conform-react/tests/state.test.ts
Fix https://github.com/edmundhung/conform/discussions/1014#discussioncomment-14366000
=> fix(conform-dom): ensure change() accepts an empty file object without error
