- examples/remix/app/routes/signup.tsx
- packages/conform-dom/index.ts
- packages/conform-react/helpers.ts
- packages/conform-react/hooks.ts
- packages/conform-zod/index.ts
Just noticed currently there is no way to setup a checkbox and map it to a boolean which should be a common need for many forms like the remember me checkbox on a login form.
- No breaking changes
- Constraint type checking is loosen as it gives no additional value
- `conform.input()` helper should now accept boolean field config. It also default to `on` if no value is provided for checkbox or radio. Same as the browser default.
> feat: add boolean checkbox support

- packages/conform-react/hooks.ts
- playground/app/components.tsx
- playground/app/config.ts
- playground/app/helpers.ts
- playground/app/root.tsx
- playground/app/routes/basic.tsx
- playwright.config.ts
- tests/basic.spec.ts
The `useForm` hook was listening to the `input` and `focusout` event on the document body to decide when to **report**. However, I notice it end up triggering the **report** earlier than the `validate` done by fieldset.
The issue is likely cause by the event listener of the fieldset being setup through React while the one for form is done manually, in which React register the event listeners on the document (or root). The event listener does not trigger in the same order as expected.
> fix: valdiate should be called before report

- packages/conform-react/hooks.ts
- playground/app/helpers.ts
- tests/basic.spec.ts
The initial version of conform has a wrong assumption in which reset event will be bubbled up and triggered the fieldset `reset` event handler. 
This fix, instead, register a reset event handler on the document and does 2 things:
1. Clear all error messages
2. Revalidate the fieldset
> fix: error messages should be cleared with fields revalidated on reset

- packages/conform-zod/index.ts
- playground/app/components.tsx
- playground/app/playground.tsx
- playground/app/routes/zod.tsx
- tests/basic.spec.ts
- tests/zod.spec.ts
This PR improves the logic on inferring constraint based on `zod` schema.
- It should manage to unwarp ZodEffect and ZodOptional correctly when inferring constraint
- it infers the constraint based on the array element type as well (Not final)
- It will no longer infer `steps` based on the `multipleOf` checks on zod number as input steps is affected by `min`, e.g. 15 will be counted as valid when step = 10 and min = 5, instead 10 will be counted as valid when step = 10 but min = 0
- It infers pattern if the type is an enum
- It infers required as false if the type has a default value
> fix(conform-zod): ensure constraint inferred from zod to be valid

- examples/remix/app/routes/order.tsx
- examples/remix/app/routes/signup.tsx
- package.json
- packages/conform-dom/index.ts
- packages/conform-react/index.ts
- packages/conform-zod/index.ts
- playground/app/components.tsx
- playground/app/playground.tsx
- playground/app/routes/basic.tsx
- playground/app/routes/zod.tsx
- playwright.config.ts
- tests/basic.spec.ts
- tests/zod.spec.ts
Conform zod resolver provides a `parse` function which lets you parse the `FormData` or `URLSearchParams` object based on the schema. The result was called `FormResult` and it has a slightly different structure based on the `state`.
The main problem here is the `value` types varies between `accepted` state and the rest. Before we let zod parse the data, we first transform the payload to a object structure based on the key of each entry. This structure should allows conform to recreate a shape similar to the expected data type except the value is always a string. This is represented by a type called
`FieldsetData<T, string>`.
```tsx
import { parse } from '@conform-to/zod';
const formData = await request.formData();
const result = parse(formData, schema);
const acceptedValue = result.state …
```
> feat!: redesign form result structure

- packages/conform-dom/README.md
- packages/conform-dom/index.ts
- packages/conform-react/hooks.ts
- packages/conform-zod/index.ts
- tests/basic.spec.ts
This PR refactors the setup in the zod resolver for the upcoming yup resolver (#15). Technically, this also introduces several breaking changes on the `conform-dom` package. Considering none of the APIs are documented. This PR would be treat as a fix instead.
> refactor: simplify zod resolver setup

- examples/remix/app/routes/material-ui.tsx
- packages/conform-dom/index.ts
- packages/conform-react/README.md
- packages/conform-react/helpers.ts
- packages/conform-react/hooks.ts
This makes `useControlledInput` returning the props to be applied on the input element instead of giving you an element directly, which gives users control over the shadow input in case of customization
Example:
```tsx
import { useFieldset, useControlledInput } from '@conform-to/react';
import { Select, MenuItem } from '@mui/material';
function MuiForm() {
const [fieldsetProps, { category }] = useFieldset(schema);
const [inputProps, control] = useControlledInput(category);
return (
<fieldset {...fieldsetProps}>
{/* Render a shadow input somewhere */}
<input {...inputProps} />
{/* MUI Select is a controlled component */}
<Select
label="Category"
value={control.value}
onChange={control.onChange}
onBlur={control.onBlur}
inputProps={{
onInvalid: …
```
> feat(conform-react)!: allow customizing shadow input with props

- examples/remix/app/routes/order.tsx
- packages/conform-dom/README.md
- packages/conform-dom/index.ts
- packages/conform-react/README.md
- packages/conform-react/helpers.ts
- packages/conform-react/hooks.ts
- packages/conform-zod/index.ts
- playground/app/fieldset.tsx
- tests/basic.spec.ts
This allows `useFieldList` to listen to the form event and reset its internal state upon receiving the reset event with implementation refactored.
The signature of the control button is also updated.
Example:
```tsx
function CollectionForm() {
const [fieldsetProps, { books }] = useFieldset(collectionSchema);
const [bookList, control] = useFieldList(fieldsetProps.ref, books);
return (
<fieldset {...fieldsetProps}>
{bookList.map((book, index) => (
<div key={book.key}>
{/* `book.props` is a FieldProps object similar to `books` */}
<BookFieldset {...book.props}>
{/* To setup a delete button */}
<button {...control.remove({ index })}>Delete</button>
</div>
))}
{/* To setup a button that can append a new row */}
<button {...control.append()}>add</button> …
```
> feat(conform-react)!: support list reset through reset event

- examples/remix/app/routes/material-ui.tsx
- examples/remix/app/routes/order.tsx
- examples/remix/app/routes/search.tsx
- examples/remix/app/routes/signup.tsx
- packages/conform-dom/index.ts
- packages/conform-react/README.md
- packages/conform-react/helpers.ts
- packages/conform-react/hooks.ts
- packages/conform-react/index.ts
- packages/conform-zod/index.ts
- playground/app/fieldset.tsx
- playground/app/playground.tsx
- playground/app/routes/basic.tsx
- playground/app/routes/zod.tsx
- tests/helpers.ts
As mentioned in #18, I was unhappy with the `useForm` hook as its purpose is not clear. It is not that useful without `useFieldset`. After trying out several new designs for almost a month, I think it's time to settled on one of them.
The idea is:
1) `useForm` is the core of conform which covers all the validation logic
2) `useFieldset` is now only responsible for monitoring field state and act as a helper for configuring fields
The API signature is almost the same comparing with the current one, except:
- `useForm` no longer accept the `onReset` property. Just use the form `onReset` event listener if needed
- `useFieldset` no longer returns the `FieldsetProps`, instead it expect a ref object of the form or fieldset element.
- The field information …
> feat(conform-react)!: api consolidation

- examples/remix/app/routes/material-ui.tsx
- examples/remix/app/routes/order.tsx
- examples/remix/app/routes/search.tsx
- examples/remix/app/routes/signup.tsx
- packages/conform-dom/index.ts
- packages/conform-zod/README.md
- packages/conform-zod/index.ts
- playground/app/routes/basic.tsx
- playground/app/routes/zod.tsx
This is a follow-up from #21 as now none of our hooks accept the schema directly but instead expect individual pieces of what schema provided. There are 2 ways to handle this:
1) Make 3 independent function that parse the schema and convert it to the corresponding structure we want.
2) Generate all 3 things in 1 function.
Although (1) is good for reducing the size of the package (since `parse` might only be needed on BE and the `constraint` is optional), I don't like having to call so many functions again and again. This PR goes with option 2 instead.
> feat(conform-zod)!: merge parse into schema to streamline form setup

- examples/remix/README.md
- examples/remix/app/routes/index.tsx
- examples/zod/README.md
- packages/conform-zod/README.md
- packages/conform-zod/index.ts
- playground/app/routes/zod.tsx
As `zod` does not have specific logic for handling form data, there are some common cases need to be handled by the users. For example,
1. it does not treat empty string as invalid for a requried field
2. it has no type coercion support (e.g. '1' -> 1)
The zod schema resolver currently does an extra cleanup step to transform empty string to undefined internally. But users are still required to do convert the data to their desired type themselves.
```tsx
import { z } from 'zod';
import { resolve, ifNonEmptyString } from '@conform-to/zod';
const schema = resolve(
z.object({
// No preprocess is needed for string as empty string
// is already converted to undefined by the resolver
text: z.string({ required_error: 'This field is required' }),
// Cast to number manually
number: z.preprocess( …
```
> feat(conform-zod): add preprocess helper

- examples/remix/app/routes/index.tsx
- packages/conform-react/hooks.ts
- tests/basic.spec.ts
This fix make `defaultValue` works consistently simialr to native input fields: Once set, any changes will be ignored until reset.
This should make customizing the default value of the field list easier. For example:
```tsx
function TodoForm() {
const formProps = useForm();
const { title, tasks } = useFieldset<Todo>(formProps.ref);
const [taskList, control] = useFieldList(formProps.ref, {
...tasks.config,
defaultValue: tasks.config.defaultValue ?? [], // default to empty list
});
return (
<form {...formProps}>
{/* ... */}
</form>
);
}
```
You can also default to different size with this:
```tsx
const [taskList, control] = useFieldList(formProps.ref, {
...tasks.config,
// default to array of size 3 with `undefined` items
defaultValue: tasks.config.defaultValue ?? Array(3).fill(),
});
```
> fix(conform-react): remove unwanted state sync in useFieldList

- examples/remix/app/routes/index.tsx
- packages/conform-dom/index.ts
- packages/conform-react/hooks.ts
- packages/conform-yup/index.ts
- packages/conform-zod/index.ts
- tests/basic.spec.ts
- tests/yup.spec.ts
- tests/zod.spec.ts
This is the first step for the upcoming server validation feature. It stops syncing error with useEffect whenever the reference for `initialError` is changed with the error object simplified to a name-message pair array (i.e. `Array<[string, string]>`). It also makes sure a stable reference for `defaultValue`.
The usage of the new error structure will be covered in another PR.
These values will not be refreshed unless a form `reset` event is captured.
> feat(conform-dom,conform-react,conform-yup,conform-zod)!: make internal state uncontrolled

- README.md
- examples/basics/README.md
- examples/basics/src/App.tsx
- examples/list/src/App.tsx
- examples/material-ui/src/App.tsx
- examples/nested/src/App.tsx
- examples/remix/app/routes/index.tsx
- examples/server-validation/app/routes/index.tsx
- examples/validation/src/App.tsx
- examples/yup/src/App.tsx
- examples/zod/src/App.tsx
- packages/conform-dom/index.ts
- packages/conform-react/hooks.ts
- packages/conform-react/index.ts
- packages/conform-yup/index.ts
- packages/conform-zod/index.ts
- playground/app/components.tsx
- playground/app/config.ts
- playground/app/routes/employee.tsx
- playground/app/routes/login.tsx
- playground/app/routes/movie.tsx
- playground/app/routes/payment.tsx
- playground/app/routes/signup.tsx
- playground/app/routes/student.tsx
- playground/app/routes/todos.tsx
- tests/conform-dom.spec.ts
- tests/helpers.ts
- tests/react.spec.ts
Time to settle on an API and ship it.
1. Introduce validation `mode` config on the `useForm` hook Default to `client-only`, which calls `even.preventDefault()` for you and prevent the `onSubmit` from being triggered by validation. This helps removing unnecessary boileplate when no server-validation is needed. 
2. Simplified the submission interface by removing the concept of `scope`
3. New `shouldValidate(submission: Submission): boolean` helper. Mainly used for server validation
4. The `onValidate()` function no longer need to returns a boolean. The official way to skip reporting client error is to `throw`. For now, throwing the `form` element will avoid conform form reporting the exception caught on console. (Not sure how to make this better yet...)
```tsx
import type { Submission } …
```
> feat!: finialize server validation mode

- packages/conform-react/hooks.ts
- playground/app/components.tsx
Fix #56 
The issue was that non-submit button will always return empty string for `element.validationMessage` regardless if conform ever tries to set the error with `element.setCustomValidity(message)`. This can be avoided by checking `element.willValidate` first.
> fix(conform-react): form error should ignore elements with willValidate false

- packages/conform-dom/index.ts
- packages/conform-react/hooks.ts
- This makes conform inserting placeholder buttons for non-field error if no existing elements can be used, e.g. form error.
- Instead of relying on submit event to reset error due to no invalid event being dispatched by native APIs like `form.reportValidity()` on field changed to valid state, this is now simplified by dispatching invalid event manually whenever the `validationMessage` is changed.
> feat(conform-dom,conform-react): automatic button creation for form-level error

- packages/conform-react/README.md
- packages/conform-react/hooks.ts
- playground/app/routes/simple-list.tsx
- tests/helpers.ts
- tests/integrations/simple-list.spec.ts
This PR adds error capturing logic for each list item, which is useful when dealing with simple array structure like `string[]`
```tsx
const [list, command] = useFieldList(form.ref, items.config);
return (
<ol>
{list.map(item => (
<li key={item.key}>
<input {...conform.input(item.config)} />
{item.error}
</li>
)}
</ol>
);
}
> feat(conform-react): capture list item error

- packages/conform-dom/index.ts
- packages/conform-react/helpers.ts
- playground/app/routes/file-upload.tsx
- tests/integrations/file-upload.spec.ts
My original idea was to use `[]` to denote the type of the data and hopefully enable a better type hint on the parsed value, but then comes to realize the current types for `submission.value` is very much a lie as there is no way to guess its structure, best as `Record<string, unknown>`.
- The final solution simply removes the error thrown when there are more than one entry with the same name and convert the value to an array instead. This means the result data type will be an array **ONLY** when there are 2+ entries. It is the duty of the user to coerce the value to an array if appropriate. 
- The FormData API will generate an entry with empty file (name = '', size = 0, type = 'application/octet-stream') even no file is selected. However, there is currently a bug on …
> feat(conform-dom,conform-react): multiple file support

- README.md
- docs/basics.md
- docs/submission.md
- docs/validation.md
- examples/basic/src/App.tsx
- examples/chakra-ui/src/App.tsx
- examples/headless-ui/src/App.tsx
- examples/material-ui/src/App.tsx
- examples/remix-run/app/routes/async-validation.tsx
- examples/remix-run/app/routes/server-validation.tsx
- examples/remix-run/app/routes/todos.tsx
- examples/remix-run/app/routes/zod.tsx
- examples/todos/src/App.tsx
- examples/yup/src/App.tsx
- examples/zod/src/App.tsx
- packages/conform-react/README.md
- packages/conform-react/hooks.ts
- packages/conform-yup/README.md
- packages/conform-zod/README.md
- playground/app/routes/employee.tsx
- playground/app/routes/file-upload.tsx
- playground/app/routes/login.tsx
- playground/app/routes/movie.tsx
- playground/app/routes/payment.tsx
- playground/app/routes/signup.tsx
- playground/app/routes/simple-list.tsx
- playground/app/routes/student.tsx
- playground/app/routes/todos.tsx
This is a change I have been considering since v0.3. What changed is just calling `useFieldset()` inside `useForm()` and return the data as a tuple:
```tsx
// Before
export default function LoginForm() {
const form = useForm({
onValidate({ form, formData }) {
return validate(formData, schema);
},
});
const { email, password } = useFieldset(form.ref, form.config);
return (
<form {...form.props}>
{/* ... */}
</form>
);
}
// After the changes
export default function LoginForm() {
const [form, { email, password }] = useForm({
onValidate({ form, formData }) {
return validate(formData, schema);
},
});
return (
<form {...form.props}>
{/* ... */}
</form>
);
}
```
> feat(conform-react)!: return fieldset on useForm hook

- packages/conform-dom/index.ts
- playground/app/routes/radio-buttons.tsx
- tests/integrations/radio-buttons.spec.ts
This bug is introduced with #69 which throws an error if there are multiple fields with the exact same name. As there could be only one error message per name and so there is no way to provide a different message for each input. However, this is not a problem with radio buttons.
> fix: radio buttons support

- README.md
- docs/tutorial.md
- examples/async-validation/README.md
- examples/nested-list/README.md
- examples/server-validation/README.md
- examples/yup/README.md
- examples/zod/README.md
In order to showcases the features of Conform with Remix, I have migrated many of the examples to Remix running on sandbox container. However some of the examples seems to be stuck in `Initializing Sandbox Container` stage forever and the only way to solve it now is by forking it. Adding a reminder so users can still give it a try.
> docs: add reminder for sandbox container examples

- docs/focus-management.md
- docs/integrations.md
- examples/chakra-ui/README.md
- examples/chakra-ui/src/App.tsx
- examples/headless-ui/README.md
- examples/headless-ui/src/App.tsx
- examples/material-ui/README.md
- examples/material-ui/src/App.tsx
- packages/conform-dom/index.ts
- packages/conform-react/README.md
- packages/conform-react/helpers.ts
- packages/conform-react/hooks.ts
- playground/app/routes/input-event.tsx
- tests/integrations/input-event.spec.ts
This APIs has several improvements over **useControlledInput()**:
- It no longer enforces creating a shadow input element
- Use your own value instead of built-in value state
- Explicit focus forwarding for flexiblity
- Wider event type support, e.g. focus-in / focus / focus-out / change (react-only)
```tsx
// Before
function ExampleAutocomplete({ label, error, ...config }: FieldProps<string>) {
const [shadowInput, control] = useControlledInput(config);
return (
<>
<input {...shadowInput} />
<Autocomplete
disablePortal
options={['The Godfather', 'Pulp Fiction']}
value={control.value}
onChange={(_, option) => control.change(`${option ?? ''}`)}
renderInput={(params) => (
<TextField
{...params}
label={label}
inputRef={control.ref}
onBlur={control.blur}
error={Boolean(error)} …
```
> feat(conform-react): useInputEvent API

- packages/conform-dom/index.ts
- packages/conform-react/hooks.ts
- playground/app/routes/simple-list.tsx
- playground/app/routes/todos.tsx
- tests/integrations/simple-list.spec.ts
> Draft. It might very likely includes a breaking change..
Tasks:
~~I might need an alternative solution here as the current solution removes the button before the form is submitted when deleting a row. Remix is unhappy about it and throw an error as the form submitter is no longer belongs to the form since it is unmounted.~~
close #62
> feat(conform-react): list validation 

- README.md
- docs/intent-button.md
- docs/validation.md
- examples/async-validation/app/routes/index.tsx
- examples/nested-list/app/routes/index.tsx
- examples/server-validation/app/routes/index.tsx
- examples/yup/app/routes/index.tsx
- examples/zod/app/routes/index.tsx
- guide/app/routes/_guide.tsx
- packages/conform-dom/index.ts
- packages/conform-react/README.md
- packages/conform-react/helpers.ts
- packages/conform-react/hooks.ts
- packages/conform-react/index.ts
- packages/conform-yup/README.md
- packages/conform-zod/README.md
- playground/app/routes/employee.tsx
- playground/app/routes/login.tsx
- playground/app/routes/movie.tsx
- playground/app/routes/payment.tsx
- playground/app/routes/signup.tsx
- playground/app/routes/todos.tsx
- playground/app/routes/validate.tsx
- tests/conform-dom.spec.ts
- tests/integrations/file-upload.spec.ts
- tests/integrations/radio-buttons.spec.ts
- tests/integrations/simple-list.spec.ts
- tests/integrations/validate.spec.ts
- tests/react.spec.ts
This merges `submission.type` with `submission.intent` to align with the intent button approach that are common in Remix. More changes coming with the validation setup.
> feat(conform-react)!: simplify intent

- docs/validation.md
Because it broke the sidebar link.
> Fix header spelling

- README.md
- docs/tutorial.md
- docs/validation.md
- examples/async-validation/app/routes/index.tsx
- examples/server-validation/app/routes/index.tsx
- packages/conform-dom/index.ts
- packages/conform-react/README.md
- packages/conform-react/helpers.ts
- packages/conform-react/hooks.ts
- packages/conform-react/index.ts
- packages/conform-yup/index.ts
- packages/conform-zod/index.ts
- playground/app/components.tsx
- playground/app/routes/attributes.tsx
- playground/app/routes/employee.tsx
- playground/app/routes/login.tsx
- playground/app/routes/movie.tsx
- playground/app/routes/multiple-errors.tsx
- playground/app/routes/payment.tsx
- playground/app/routes/radio-buttons.tsx
- playground/app/routes/signup.tsx
- tests/conform-dom.spec.ts
- tests/conform-yup.spec.ts
- tests/conform-zod.spec.ts
- tests/integrations/file-upload.spec.ts
- tests/integrations/multiple-errors.spec.ts
- tests/integrations/radio-buttons.spec.ts
- tests/integrations/simple-list.spec.ts
- tests/integrations/validate.spec.ts
- tests/react.spec.ts
> This PR includes breaking change
I still have a few more changes planned for the `parse` function. This PR introduces a new `resolve` option with a new error structure to support multiple errors:
Here is how you will validate a simple signup form with custom validation:
```tsx
import { parse } from '@conform-to/react';
export async function action({ request }: ActionArgs) {
const formData = await request.formData();
const submission = parse(formData, {
resolve({ email, password, confirmPassword }) {
// Instead of an array, error is now a simple dictionary
// The key should be the path while the value would be the corresponding message
const error: Record<string, string | string[]> = {};
if (!email) {
error.email = 'Email is required';
} else if (!email.includes('@')) {
error.email = …
```
> feat!: multiple errors support

- packages/conform-react/README.md
- packages/conform-react/hooks.ts
The `useControlledInput` was deprecated on v0.5.1 and should be removed from the upcoming v0.6.
> feat(conform-react)!: remove useControlledInput

- packages/conform-dom/index.ts
- packages/conform-react/helpers.ts
- packages/conform-react/hooks.ts
- packages/conform-react/index.ts
- playground/app/routes/employee.tsx
- playground/app/routes/input-attributes.tsx
- tests/helpers.ts
- tests/react.spec.ts
This PR removes the need of `shouldSubmissionPassthrough` as implemented on #95 and the `shouldValidate` config as proposed on #98 which tried to solve the questions: **What isn't validated and why**.
All the previous approaches are hard to maintain. It also introduce additional effort for user that don't need those functionalities. Now, the new approach make it totally opt-in. These questions are not required unless the form requires expensive validation or if it could only be run on the server.
Here is a quick example how to utilise the new special messages (`conform.VALIDATION_SKIPPED` and `conform.VALIDATION_UNDEFINED`) with zod:
```tsx
import { conform, useForm } from '@conform-to/react';
import { parse } from '@conform-to/zod';
import { z } from 'zod';
// Instead of sharing a …
```
> feat(conform-dom,conform-react)!: introduce validation skipped and undefined messages

- docs/intent-button.md
- packages/conform-dom/index.ts
- packages/conform-react/helpers.ts
- packages/conform-react/hooks.ts
- packages/conform-react/index.ts
Conform can already focus on first invalid field. But there is an exception I made originally to NOT changing the focus if you are already focusing on one of the field (i.e. pressing enter directly).
This PR removes the exception to align with how native error bubble works.
> feat(conform-dom): focus first non button invalid field

- packages/conform-react/hooks.ts
- playground/app/components.tsx
- playground/app/routes/file-upload.tsx
- playground/app/routes/input-attributes.tsx
- playground/app/routes/login.tsx
- playground/app/routes/simple-list.tsx
- tests/integrations/input-attributes.spec.ts
As requested on #108, Conform will set both `aria-invalid` and `aria-describedby` to the form element if there is any form error. It also provides `form.errorId` to be used as the id of the form error element.
The current implementation relies on `aria-describedby` due to [limited support](https://a11ysupport.io/tech/aria/aria-errormessage_attribute) on `aria-errormessage`
> feat(conform-react): form aria-attributes support

- packages/conform-react/hooks.ts
- playground/app/routes/input-attributes.tsx
Requested on #108.
This allows user to provide their own ref object for the form element. If it is not provided, conform will fallback to its own ref object instead.
> feat(conform-react): accept custom ref object

- docs/tutorial.md
- examples/material-ui/src/App.tsx
- examples/react-router/src/login.tsx
- packages/conform-react/README.md
- packages/conform-react/hooks.ts
- playground/app/config.ts
- playground/app/routes/validation-flow.tsx
- tests/helpers.ts
- tests/integrations/validation-flow.spec.ts
- tests/react.spec.ts
Resolves #125 
This introduces two new config on the `useForm` hooks:
```tsx
const [form, { email, password }] = useForm({
// This is now deprecated in favor of the new config
initialReport: 'onBlur',
// Define when Conform should start validation. Default `onSubmit`.
shouldValidate: 'onBlur',
// Define when Conform should revalidate again. Default `onInput`.
shouldRevalidate: 'onBlur',
});
}
```
> feat(conform-react): custom revalidation

- packages/conform-dom/index.ts
- packages/conform-react/helpers.ts
- packages/conform-react/hooks.ts
- playground/app/routes/input-attributes.tsx
- tests/integrations/input-attributes.spec.ts
Resolve #120
This adds support of `descriptionId` which could be used to setup an input hint similar to the existing `errorId`. But to utilize it, it is also required to provide an extra option `description: true` to the conform helpers which will setup the `aria-describedby` accordingly.
```tsx
<input {...conform.input(email, { type: "email" })} />
// If valid, no aria attributes will be set
// If invalid, aria-invalid="true" aria-describedby="errorId"
<input {...conform.input(email, { type: "email", description: true })} />
// If valid, aria-describedby="descriptionId"
// If invalid, aria-invalid="true" aria-describedby="errorId descriptionId"
```
> feat(conform-react): add support of descriptionId

- package-lock.json
- package.json
- packages/conform-validitystate/.npmignore
- packages/conform-validitystate/README.md
- packages/conform-validitystate/index.ts
- packages/conform-validitystate/package.json
- packages/conform-validitystate/tsconfig.json
- playground/app/components.tsx
- playground/app/routes/validitystate.tsx
- playground/package.json
- rollup.config.js
- tests/integrations/validitystate.spec.ts
> I am developing this mainly for my upcoming talk on Remix Conf.
This enables type-checking your form constraint and validate on the server using the same rules as the browser. It implements all the input types except `month` and `week`. 
The solution focus on enabling validation with native browser constraint whenever it is applicable.
> Intent to ship: @conform-to/validitystate

- packages/conform-zod/index.ts
- tests/conform-zod.spec.ts
It should merge the derived constraint from both side with the right one override the left one.
```tsx
const constraint = getFieldsetConstraint(
z
.object({ a: z.string() })
.and(z.object({ a: z.string().optional(), b: z.string() }))
);
// { a: { required: false }, b: { required: true } }
```
> feat(conform-zod): support intersection with getFieldsetConstraint

- packages/conform-dom/intent.ts
- packages/conform-react/hooks.ts
- playground/app/routes/validation-flow.tsx
- tests/conform-dom.spec.ts
- tests/integrations/validation-flow.spec.ts
This might fix the issue on #150.
> fix: form validate intent should not be considered as submitting

- .gitignore
- package.json
- packages/conform-dom/index.ts
- packages/conform-dom/intent.ts
- packages/conform-dom/package.json
- packages/conform-dom/parse.ts
- packages/conform-dom/tsconfig.json
- packages/conform-react/helpers.ts
- packages/conform-react/index.ts
- packages/conform-react/package.json
- packages/conform-react/tsconfig.json
- packages/conform-validitystate/package.json
- packages/conform-validitystate/tsconfig.json
- packages/conform-yup/package.json
- packages/conform-yup/tsconfig.json
- packages/conform-zod/package.json
- packages/conform-zod/tsconfig.json
- rollup.config.js
This tries to fix the type issues from #159 by masquerading the types as CJS as explained on https://github.com/gvergnaud/ts-pattern/pull/155#issuecomment-1537135616.
Another reference on how typescript works with ESM/CJS: https://github.com/microsoft/TypeScript/issues/49299
> build: ESM types masquerading

- docs/configuration.md
- docs/intent-button.md
- packages/conform-dom/dom.ts
- packages/conform-dom/index.ts
- packages/conform-dom/intent.ts
- packages/conform-dom/parse.ts
- packages/conform-dom/types.ts
- packages/conform-react/README.md
- packages/conform-react/hooks.ts
- playground/app/routes/validate.tsx
- tests/conform-dom.spec.ts
- tests/integrations/validate.spec.ts
This includes two breaking changes that I believe no one is relying on 😅 
- Drop support of form validate intent (i.e. `validate()`). This shouldn't exist from the start as we can achieve the same thing with a custom intent.
- Drop support of autofocus when clicking on a button with the field validate intent (i.e. `validate(name)`). This requires a fair amount of code to work currently which doesn't justify its usage.
> refactor!: simplify intent setup

- packages/conform-zod/index.ts
- tests/conform-zod.spec.ts
This adds basic zod union / discriminatedUnion support when inferring constraint.
Example:
```ts
const schema = z
.discriminatedUnion('type', [
z.object({ type: z.literal('a'), foo: z.string().min(1, 'min'), baz: z.string().min(1, 'min') }),
z.object({ type: z.literal('b'), bar: z.string().min(1, 'min'), baz: z.string().min(1, 'min') }),
])
.and(
z.object({
qux: z.string().min(1, 'min'),
}),
),
// Both `foo` and `bar` is considered optional now
// But `baz` and `qux` remains required  
expect(getFieldsetConstraint(schema)).toEqual({
type: { required: true },
foo: { required: false, minLength: 1 },
bar: { required: false, minLength: 1 },
baz: { required: true, minLength: 1 },
quz: { required: true, minLength: 1 },
});
```
> feat(conform-zod): union inference support

- packages/conform-react/hooks.ts
- playground/app/components.tsx
- playground/app/routes/reset-default-value.tsx
- tests/integrations/reset-default-value.spec.ts
Before this change, the idiomatic way to reset a form when the submission is successful is done by triggering form reset just like how the Remix community suggested generally:
```ts
const actionData = useActionData();
const navigation = useNavigation();
const [form, fields] = useForm({
lastSubmission: actionData?.submission,
});
useEffect(() => {
if (navigation.state === 'idle' && actionData?.success) {
formRef.current?.reset();
}
}, [actionData?.success, navigation.state])
```
However, this does not work in a NoJS environement as the effect will never run while the form is still using the last submission as the default value of the form. Here is the new solution:
```ts
const actionData = useActionData();
const [form, fields] = useForm({
// Pass the submission only if the action was …
```
> feat(conform-react): auto reset when last submission reset

- packages/conform-react/helpers.ts
- playground/app/routes/input-attributes.tsx
```tsx
// Before
const [form, { message }] = useForm();
return (
<form>
<input
{...conform.input(message, {
type: 'text',
})}
/>
</form>
)
}
// After
const [form, { message }] = useForm();
return (
<form>
<input
{...conform.input(message, {
type: 'text',
ariaAttributes: true, // default to `false`
})}
/>
</form>
)
}
```
> feat(conform-react)!: stop deriving aria attribute by default

- packages/conform-react/README.md
- packages/conform-react/hooks.ts
- playground/app/routes/movie.tsx
- playground/app/routes/payment.tsx
- playground/app/routes/signup.tsx
- playground/app/routes/validate-constraint.tsx
- tests/integrations/custom-inputs.spec.ts
- tests/integrations/validation-flow.spec.ts
This changes the default of the `shouldRevalidate` config on the `useForm` hook from `onInput` to be based on the current `shouldValidate` config.
- If `shouldValidate` is not configured, the default would be `onSubmit` and so `shouldRevalidate` will also default to `onSubmit`
- If `shouldValidate` is set to `onBlur` or `onInput`, then `shouldRevalidate` will default to `onBlur` or `onInput` resepectively.
> feat(conform-react)!: improve default shouldRevalidate config

- packages/conform-react/hooks.ts
- playground/app/routes/reset-default-value.tsx
Fix #191
On [v0.7.0](https://github.com/edmundhung/conform/releases/tag/v0.7.0), we introduced an approach to reset the form automatically by tracking when the last submission value is cleared.
```tsx
const actionData = useActionData();
const [form, fields] = useForm({
// Pass the submission only if the action was failed
// Or, skip sending the submission back on success
lastSubmission: !actionData?.success ? actionData?.submission : null,
});
```
But there is a pitfall here which I overlooked. If the submission has been successful consecutively, the internal `useEffect` call will not be executed as it is still receiving the same `null` value and thus no reset happens.
This PR use a different approach to trigger form reset:
```tsx
export let action = async ({ request }: ActionArgs) => { …
```
> refactor: utilize submission payload for form reset instead

- packages/conform-zod/index.ts
- tests/conform-zod.spec.ts
Fix #207.
The refine helper should run the refinement if the `when` option is undefined.
> fix(conform-zod): refine should be run by default

- packages/conform-react/helpers.ts
- tests/conform-react.spec.ts
Resolve #214
```tsx
import { conform } from '@conform-to/react';
<fieldset {...conform.fieldset(field, { ariaAttributes: true })>
// This is equivalent to:
<fieldset id={field.id} name={field.name} form={fieldset.form} aria-invalid={...} aria-describedby={...}> 
```
> feat(conform-react): implement fieldset helper

- packages/conform-dom/formdata.ts
- packages/conform-dom/parse.ts
- packages/conform-zod/README.md
- packages/conform-zod/index.ts
- playground/app/routes/async-validation.tsx
- playground/app/routes/custom-inputs.tsx
- playground/app/routes/file-upload.tsx
- playground/app/routes/index.tsx
- playground/app/routes/multiple-errors.tsx
- playground/app/routes/payment.tsx
- playground/app/routes/reset-default-value.tsx
- playground/app/routes/simple-list.tsx
- playground/app/routes/todos.tsx
- playground/app/routes/validate.tsx
- playground/app/routes/validation-flow.tsx
- tests/conform-zod.spec.ts
Fix #196.
This adds an extra option on `parse` to strip all empty value. This is an opt-in feature for now and very likely the default on v0.8.
```tsx
// Instead of this:
const schema = z.object({
text: z.string().min(1, 'Email is required');
});
const submission = parse(formData, { schema });
// Do this:
const schema = z.object({
email: z.string({ required_error: 'Email is required'),
});
const submission = parse(formData, { schema, stripEmptyValue: true });
```
> feat(conform-zod): strip empty value

- packages/conform-zod/README.md
- packages/conform-zod/index.ts
- playground/app/routes/async-validation.tsx
- playground/app/routes/custom-inputs.tsx
- playground/app/routes/file-upload.tsx
- playground/app/routes/index.tsx
- playground/app/routes/multiple-errors.tsx
- playground/app/routes/payment.tsx
- playground/app/routes/reset-default-value.tsx
- playground/app/routes/simple-list.tsx
- playground/app/routes/todos.tsx
- playground/app/routes/validate.tsx
- playground/app/routes/validation-flow.tsx
See https://github.com/edmundhung/conform/issues/196#issuecomment-1638780512
> feat(conform-zod)!: default stripEmptyValue option to true

- packages/conform-react/hooks.ts
- packages/conform-yup/index.ts
- packages/conform-zod/index.ts
- playground/app/routes/async-validation.tsx
- playground/app/routes/multiple-errors.tsx
- playground/app/routes/validate-constraint.tsx
- tests/conform-yup.spec.ts
- tests/conform-zod.spec.ts
- tests/integrations/validate-constraint.spec.ts
> feat(conform-react,conform-zod,conform-yup)!: multiple errors by default

- packages/conform-react/hooks.ts
Original comment suggests that `"onChange"` is allowed, while it's actually `"onInput"`
> docs: update comments for (re)validation

- docs/checkbox-and-radio-group.md
- examples/react-router/src/todos.tsx
- packages/conform-zod/coercion.ts
- playground/app/routes/payment.tsx
- tests/conform-zod.spec.ts
- tests/react.spec.ts
I think it would be too aggresive if conform coerce anything truthy to true. This restrict it to `on` only (i.e. the default value of checkbox). If there is a need to use custom value, it is better to be explicit:
```tsx
import { conform, useForm } from '@conform-to/react';
import { parse } from '@conform-to/zod';
import { z } from 'zod';
const schema = z.object({
confirmed: z.string().transform(value => value === 'yes'),
});
const [form, { confirmed }] = useForm({
onValidate({ formData }) {
return parse(formData, { schema });
},
});
return (
<form {...form.props}>
{/* Example 1: Custom checkbox value */}
<div>
<label>Confirm</label>
<input {...conform.input(confirmed, { type: 'checkbox', value: 'yes' })} />
<div>{confirmed.error}</div>
</div>
{/* Example 2: …
```
> feat: restrict boolean coercion

- docs/checkbox-and-radio-group.md
I noticed some typos when I was copy/pasting this into my app to test it out.
> fix: typos in checkbox docs

- packages/conform-zod/coercion.ts
- tests/conform-zod.spec.ts
> fix(conform-zod): coerce file only if File class is defined

- packages/conform-zod/coercion.ts
- packages/conform-zod/parse.ts
- tests/conform-zod.spec.ts
Conform should coerce value with `.default()` similar to how `.optional()` works.
> fix(conform-zod): zod default support

- examples/remix/package.json
- package-lock.json
- packages/conform-zod/coercion.ts
- packages/conform-zod/package.json
This seems to get around the current bug on __zod v3.22__ with regards to `.preprocess()`.
Fix #271, #280
References:
- https://github.com/colinhacks/zod/issues/2677
- https://github.com/colinhacks/zod/issues/2671
> fix(conform-zod): avoid using preprocess

- packages/conform-react/hooks.ts
- playground/app/routes/simple-list.tsx
- tests/integrations/simple-list.spec.ts
This fixes a bug occurring during client validation, that originates from a missing case for the new `list.insert` method in the `useFieldList` hook.
> fix: add missing case in useFieldList

- packages/conform-dom/parse.ts
The Jsonify utility used by Remix will make a `Record<string, any>` disappear in the type: https://github.com/remix-run/remix/issues/7246
But considering this further, "unknown" is a safer option for this type anyway because it avoids issues with accidentally accessing the values off the submission payload without first checking them. So I do think this change should be made.
> fix(ts): set payload to unknown value type

- docs/integrations.md
I was reading through the docs and based on the indentation, it seems the elements that were supposed to contain the error messages from `confirm` were not closed.
> docs: Add closing </div> tags to HTML snippet

- packages/conform-react/hooks.ts
In Remix, there may be times when you need to return json(null), which is often what Remix expects. If you return json(undefined), the loaders are not refetched. To resolve this issue, accepting null for "lastsubmission" keeps TypeScript happy and ensures the loader is refetched.
> Update hooks.ts lastsubmission to accept null value

- docs/validation.md
The async validation example imports `refine` from `@conform-to/react` instead of `@conform-to/zod`
> docs: fix async validation example imports

- packages/conform-zod/README.md
Just adding a missing link to `refine` in the  **API Reference** sidebar inside the `@conform-to/zod` docs. 🙂
> docs(conform-zod): add missing `refine` link to sidebar

- docs/tutorial.md
There were various grammar issues with missing words and missing imports.
> docs: update typos and grammar in tutorial

- packages/conform-dom/form.ts
- packages/conform-react/helpers.ts
- Remove `image` as an accepted value for input `type`.
- Add `undefined` as an accepted value for `lastResult`, for improved compatibility with TypeScript's `exactOptionalPropertyTypes`.
> Type fixes

- docs/integration/ui-libraries.md
With the new version the fieldName.error was renamed to fieldName.errors
> docs: fix error property in 'UI library' documentation

- packages/conform-dom/form.ts
- packages/conform-dom/formdata.ts
- packages/conform-dom/submission.ts
- playground/app/routes/async-validation.tsx
- tests/integrations/async-validation.spec.ts
We normalized the submission error and remove all `null` accidentally. This makes Conform fail to find out whether validation is skipped and consider the field valid instead.
> fix(conform-react): submission reply should not remove null from error

- docs/README.md
- docs/api/react/FormProvider.md
- docs/api/react/getCollectionProps.md
- docs/api/react/getSelectProps.md
- docs/api/react/getTextareaProps.md
- docs/api/react/useForm.md
- docs/api/react/useInputControl.md
- docs/api/validitystate.md
- docs/api/zod/conformZodMessage.md
- docs/integration/ui-libraries.md
- docs/intent-button.md
- docs/overview.md
- docs/tutorial.md
- docs/upgrading-v1.md
Love this library!
This PR corrects a few misspelled words in the docs.
> Misc. spelling updates

- packages/conform-dom/form.ts
Conform has been unnecessarily strict in checking whether the form element is available and throw an error if the form element is not rendered, e.g. modal form. This fix the issue.
> fix(conform-dom): conform should work even the form element is not available

- packages/conform-dom/form.ts
- packages/conform-dom/submission.ts
- playground/app/routes/form-control.tsx
- tests/integrations/form-control.spec.ts
All value within Conform should be serialized.
This fix an issue with `form.update` not working properly with non string value. As `getInputProps` skip setting the default value if the `initialValue` is not string.
> fix(conform-dom): form update value should be serialized

- examples/headless-ui/src/App.tsx
- packages/conform-dom/form.ts
- packages/conform-react/integrations.ts
- playground/app/routes/custom-inputs.tsx
- tests/integrations/custom-inputs.spec.ts
This fixes #389 and #401.
But there is one minor issue with multi select. As the `initialValue` could be `string` instead of `string[]` in one edge case in which user select only one item AND submit the form AND a full document reload happened. This is because conform have no idea this field is an array and only find one entry from the FormData. 😅 
There are a few options:
1. Let user deal with it like how I did on the `headless-ui` example:
```tsx
const control = useInputControl(meta);
// To make it an array...
const value = typeof control.value === 'undefined'
? []
: Array.isArray(control.value)
? control.value
: [control.value];
```
2. Add a new properties to the `control` object which wraps the logic above, e.g. `control.valueAsArray`
3. Help user lie 😅 This is an edge case, …
> fix(conform-react): useInputControl should populate initial value and support mult select

- packages/conform-zod/coercion.ts
- tests/conform-zod.spec.ts
This makese zod coerce a multi select with empty value option correctly and returns __nonEmpty__ message from `items` instead of __required__ from `items[0]`.
```tsx
const schema = z.object({
items: z.string().array().nonEmpty('At least one item is required')
});
```
> fix(conform-zod): multi select coercion

- docs/api/react/FormProvider.md
- docs/api/react/FormStateInput.md
The documentation for 'FormStateInput' and 'FormProvider' had a mistake in the import statement, 
so I corrected it. It seems that '@conform-to/react' was changed to '@remix-run/react'.
> fix: Update FormProvider.md and FormStateInput.md

- packages/conform-dom/form.ts
- packages/conform-dom/formdata.ts
> fix: file should not be cleared unless it is empty

- packages/conform-react/helpers.ts
- packages/conform-react/index.ts
- packages/conform-react/integrations.ts
- playground/app/routes/custom-inputs.tsx
- playground/app/routes/input-event.tsx
- tests/integrations/custom-inputs.spec.ts
As reported on #306, #401, #443, the auto insert input feature on `useInputControl` is found to be problematic in several situations where you need to dynamically render the input. The current design is also not flexible in handling these cases. Although we can consider adding extra options to `useInputControl` for handling each cases, I believe it would be better stop supporting this and have developers deciding how they wanna render the hidden input themselves similar to the `useInputEvent` hook before v1.
As this would be a breaking change if we remove the feature directly from `useInputControl`, the react package will now export an additional `useControl` hook that works exactly the same as `useInputControl` except it will never insert an hidden input for you.
This is currently named …
> feat(conform-react): unstable useControl hook

- docs/tutorial.md
Change \<form\> to \<Form\> since the Remix Form component is used in the tutorial.
This already was in place for all code samples except for one instance.
> Fix codesample typo in tutorial.md

- packages/conform-react/helpers.ts
This PR fixes some typo in `@see` link.
Thank you for great library!
> docs: fix typo in helpers.ts

- docs/api/react/getInputProps.md
- docs/api/react/getSelectProps.md
- docs/api/react/getTextareaProps.md
- docs/api/react/useInputControl.md
- docs/validation.md
This PR corrects some typo.
I have used since version 0, it became even more user-friendly with version 1. Thank you for your library.
> docs: Correct "field." to "fields." and "validate" to "validates"

- packages/conform-dom/form.ts
- packages/conform-dom/submission.ts
- tests/conform-dom.spec.ts
- tests/integrations/async-validation.spec.ts
- tests/integrations/collection.spec.ts
- tests/integrations/custom-inputs.spec.ts
- tests/integrations/file-upload.spec.ts
- tests/integrations/parse-with-yup.spec.ts
- tests/integrations/simple-list.spec.ts
Resolves #494.
This ensures Conform to work properly even if the form state is missing from the FormData object.
> feat: ensure state to be optional

- packages/conform-dom/formdata.ts
- packages/conform-dom/submission.ts
- playground/app/routes/metadata.tsx
- tests/integrations/metadata.spec.ts
Fix #469 and #487.
This reverts changes on #457. We will now preserve the file on submission result only if it is running on the client (i.e. client validation)
> fix: preserve files only on client

- packages/conform-dom/form.ts
- packages/conform-react/hooks.ts
- packages/conform-react/package.json
- playground/app/components.tsx
- playground/app/routes/form-control.tsx
- pnpm-lock.yaml
- tests/integrations/form-control.spec.ts
Fix #400.
This ensures all form intent applies to the latest form data in case multiple intents are dispatched in one single callback. Note: This only works with client validation in place in which an update can be triggered synchronously.
> fix: wrap form control in flush sync

- packages/conform-dom/form.ts
- packages/conform-react/hooks.ts
- packages/conform-react/package.json
- playground/app/components.tsx
- playground/app/routes/form-control.tsx
- pnpm-lock.yaml
- tests/integrations/form-control.spec.ts
Reverts edmundhung/conform#496. Fix #512
> Revert "fix: wrap form control in flush sync"

- guide/app/layout.tsx
- guide/app/root.tsx
This PR switches most font in the documentation website from mono to variable-width font. I think variable-width paragraphs are generally easier to read, and with variable-width paragraphs, it's also easier to glance and see what part of the documentation site is code versus context.
This ultimately comes down to preference, and I defer to the library author. No hard feelings if this is closed!
> Consider using a variable-width font for docs

- packages/conform-dom/form.ts
Fix #524.
When a dialog is closed, we might lose focus from the input and trigger validation while the form element is already unmounted. This makes sure form validation will only happens if the form element is still connected to the DOM.
> fix: validate only if the form element is mounted

- guide/app/layout.tsx
- guide/app/routes/$.tsx
- guide/app/routes/_index.tsx
- guide/app/util.ts
This pull request adds language switcher dropdown and Japanese language support to the Conform documentation site.
Key changes:
- Modified layout.tsx to load localized navigation menu and added language switcher dropdown
- Added allLanguages constant to define supported languages and their properties
Updated getMetadata, getFileContent, and getDocPath functions to handle language-specific logic
- Updated route files to use getDocPath for language-specific document paths
These changes enable a localized experience for Japanese users within the guide submodule, with the ability to switch between English and Japanese using the language dropdown in the header.
> feat(guide): added language switcher dropdown and Japanese language support.

- guide/app/util.ts
- guide/remix.env.d.ts
- guide/server.ts
This allows Remix to serve the docs based on the hostname and we can point the `ja` domain to the main branch as well.
> chroe(guide): detect language based on hostname

- packages/conform-dom/form.ts
- packages/conform-react/hooks.ts
- playground/app/routes/dom-value.tsx
- tests/integrations/dom-value.spec.ts
This allows Conform to watch for DOM changes and refresh the form value whenever a new form element is rendered.
> feat: observe dom update for form value

- packages/conform-dom/form.ts
- playground/app/routes/_index.tsx
- playground/app/routes/validation-flow.tsx
- tests/integrations/validation-flow.spec.ts
This minimize the chance server error get cleared simply because of moving focus out of the inputs. However, if the users type / click on any intent buttons, the errors will still be cleared because of client validation.
> feat: revalidate on blur only if changed

- packages/conform-react/hooks.ts
- playground/app/routes/subscription.tsx
> feat: make useFormMetadata accept no formId

- packages/conform-react/helpers.ts
I updated the type definitions for the `getCollectionProps` helper function to better narrow the `type` prop that is returned. This resolves #561.
I also corrected the URL to the docs in the `getCollectionProps` helper function's JSDoc comment.
> Narrow the `type` prop returned from the `getCollectionProps` helper

- packages/conform-react/helpers.ts
I updated the type annotations for the `getInputProps` helper function to better narrow the `type` prop that is returned.
This is the same change that was recently made to the `getCollectionProps` helper function. 
- #561
- #562
> Narrow the `type` prop returned from the `getInputProps` helper

- .gitignore
- packages/conform-zod/coercion.ts
- packages/conform-zod/constraint.ts
I got a weird bug report on Twitter here: https://twitter.com/Varkoffs/status/1783118133848400070
It seems to be due to a weirdness in Remix, where both the ESM and CommonJS versions of Zod are loaded and used during server initialization. Somehow a schema declared in a Remix page (using ESM) was getting passed into a `parseWithZod` call that was using CJS internally to do `instanceof` checks. Because each copy of Zod has separate class definitions, the `instanceof` checks fail. 
This is by no means an issue with conform, but one possible solution is for conform to avoid `instanceof`. There are other scenarios where both builds of a package can be loaded simultaneously. Some are described by isaacs (founder of npm) here: https://github.com/isaacs/tshy?tab=readme-ov-file#dual-package-hazard …
> Remove usage of `instanceof` for Zod schemas

- docs/tutorial.md
The variable name contains unwanted `s` (wrong: field`s`Errors / correct: fieldErrors)
> [docs] fix typo in tutorial.md

- docs/complex-structures.md
- docs/ja/complex-structures.md
Thanks to this wonderful library, our development efficiency has improved.
This PR is about the Documentation Guide - [Nested Objects and Arrays](https://conform.guide/complex-structures).
It does not work with TypeScript because the type for useForm wasn't specified.
I'd like to make some changes.
If you find them useful, please merge them.
> docs: Fix example code in the Nested Object and Array documentation

- .changeset/clean-spies-clap.md
- packages/conform-react/integrations.ts
> fix: reset registered input value on key changes

- examples/shadcn-ui/src/components/conform/Switch.tsx
This PR optimizes the Switch component in the shadcn example by replacing meta.value with control.value. This change aims to improve performance by reducing unnecessary re-renders.
Updated the Switch component to use control.value instead of meta.value
Modified the relevant code snippet as follows:
```tsx
Copy// Before
checked={meta.value === "on"}
// After
checked={control.value === "on"}
```
> Optimize Shadn Switch Component example by Using control.value

- docs/api/yup/parseWithYup.md
- docs/ja/api/yup/parseWithYup.md
The module name of the import destination was incorrect, so I fixed it.
> docs: Fix typo in parseWithYup.md

- examples/shadcn-ui/src/App.tsx
- examples/shadcn-ui/src/components/conform/ToggleGroup.tsx
this simple pr add a filed to demonstrate how to play with array values with mutilple mod toggle-group
> chore: enable multiple-type toggle-group in shadcn-ui examples

- .changeset/empty-guests-hear.md
- docs/api/zod/parseWithZod.md
- docs/ja/api/zod/parseWithZod.md
- packages/conform-zod/coercion.ts
- tests/conform-zod.spec.ts
> fix(conform-zod): empty string default value support

- .changeset/chilled-dingos-sniff.md
- packages/conform-dom/form.ts
It looks like I made a mistake in #508 when I widened `FormValue` to include `null` in some cases.  I'm reasonably confident a field's `initialValue` will never be `null`.
I noticed this when I created a component that takes `name: FieldName<string | object>`. You can see the strange behaviour here:
[TypeScript Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgVwM4FMBix0BsAmcAvnAGZQQhwBEAAgMYQB2p0IAtDBAPRToCG9GNQDcAKDGMmqeAG0Q-AJ4AjdAGUYUYEwDmAXTgBeFBmx58AHhlbdAPgAU1VhGoBKcQpXrN2nQDptYBhgflwANVDkdBE4bm44a184AB8UJnx0Um10fAkpGTh5JVUNGx0AeShy5QArdCEDYzQsHAIrH10UuAha+pgHJwgXdzFPEo6Kqt6hAKYgkPDI6Nj4xM7UnrqhLqZkXFwu5HTM7NygA)
You can see what happened when I ran `git blame` here:
<details>
</details>
Since this is a one-line change, I'm just submitting it through the …
> fix: `FormValue` should never be `null`

- .changeset/hip-actors-wink.md
- packages/conform-zod/coercion.ts
- tests/conform-zod.spec.ts
this change follows the same pattern as how booleans are coerced.
it also fixes issues with BigInt where if the value is not of a convertable value it doesn't break the app because BigInt/Symbol throw unlike the rest of the type constructors.
> feat(conform-zod): bigint coercion support

- packages/conform-dom/form.ts
- packages/conform-react/helpers.ts
- packages/conform-react/hooks.ts
- packages/conform-react/integrations.ts
Fix #600
This is my 2nd attempt to remove the need of passing the `key` to each input manually by updating the fields value automatically. As mentioned in #728...
> It means:
> 1. No more warnings from React when spreading the result of `getInputProps()`, `getSelectProps()` or `getTextareaProps()` as it will no longer include a `key`.
> 2. The `name` will become the only metadata required to be set on your inputs. The `initalValue` is required only if you care about progressive enhancement.
>
> The main challenge of this change is that Conform will trigger a re-render only when the subscribed metadata is changed and so we don't have a single place that will always re-render and runs the side effect we need. This PR resolves it by running the side effect everywhere we made a subscription …
> feat: auto field value update

- .changeset/gentle-humans-eat.md
- packages/conform-dom/submission.ts
Fix #628
This pull request replaces the `unknown` type in submission payloads. `unknown` is not compatible with Remix Single Fetch and new `defineLoader` or `defineAction` as it cannot be guaranteed that values of type `unknown` can be sent over the wire.
Removing `unknown` types addresses this issue. I've replaced it with what I think is correct but I don't know the ins and outs of this library so plz check.
Thanks!
> Replace `unknown` in submission payload

- .changeset/afraid-owls-repair.md
- packages/conform-react/hooks.ts
- playground/app/routes/form-control.tsx
- tests/integrations/form-control.spec.ts
Just noticed that Conform is overwriting the value of input buttons while verifying whether #730 is resolved with v1.2.0. 😅 
This should stop it from changing the value with all kinds of buttons.
> fix(conform-react): stop updating value of input buttons

- .github/version.sh
I am seeing `sed: can't read s/^Version [0-9]*\.[0-9]*\.[0-9]*/Version 1.2.1/: No such file or directory` on the [ci job](https://github.com/edmundhung/conform/actions/runs/10863466612/job/30147646591#step:7:49) but I can't reproduce it locally with my mac. This might be issue with how paths are resolved on different OS.
> chore: fix version script

- .github/version.sh
Follow-up for #767.
I think the issue is related to how sed behaves differently on mac and ci (linux). This used a different approach to get around the issue.
> chore: fix sed command

- package.json
- pnpm-lock.yaml
Fix E2E tests on ubuntu, e.g. [this](https://github.com/edmundhung/conform/actions/runs/12341816581/job/34440906271#step:6:50)
Looks like the `ubuntu-latest` image is updated recently with a few dependencies missing. Updating playwright version seems to fix the issue.
> chore: update playwright version

- .github/workflows/preview.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
I made #859 but the ci failed apparently with this issue ( https://github.com/nodejs/corepack/issues/612 ).
I added `npm i -g corepack@latest` to avoid the error.
> chore: upgrade corepack in ci

- .changeset/hot-geese-run.md
- docs/api/zod/coerceFormValue.md
- docs/api/zod/parseWithZod.md
- docs/ja/api/zod/coerceFormValue.md
- docs/ja/api/zod/parseWithZod.md
- guide/app/layout.tsx
- packages/conform-zod/coercion.ts
- packages/conform-zod/index.ts
- packages/conform-zod/parse.ts
- tests/conform-zod.spec.ts
This PR adds the ability to disable the default auto coercion behavior by setting the `disableAutoCoercion` option to `true` in `parseWithZod`.
```ts
const [form, fields] = useForm({
onValidate({ formData }) {
return parseWithZod(formData, {
schema,
disableAutoCoercion: true,
});
},
});
// ...
}
```
You can then manage how the form value is parsed yourself, or use the new `coerceFormValue` helper to coerce form value, like this:
```ts
import { parseWithZod, unstable_coerceFormValue as coerceFormValue } from '@conform-to/zod';
import { z } from 'zod';
// Coerce the form value with default behaviour
const schema = coerceFormValue(
z.object({
// ...
})
);
// Coerce the form value with default coercion overrided
const schema = coerceFormValue(
z.object({
ref: z.number() …
```
> feat(conform-zod): add `disableAutoCoercion` option with `coerceFormValue` helper

- .github/workflows/validate.yml
This PR adds a `validate` workflow that can validate an arbitrary pre-release version against the Epic Stack.
> chore: validate workflow

- .changeset/brave-timers-walk.md
- packages/conform-valibot/coercion.ts
- packages/conform-valibot/tests/coercion/schema/looseObject.test.ts
- packages/conform-valibot/tests/coercion/schema/looseObjectAsync.test.ts
- packages/conform-valibot/tests/coercion/schema/object.test.ts
- packages/conform-valibot/tests/coercion/schema/objectAsync.test.ts
- packages/conform-valibot/tests/coercion/schema/objectWithRest.test.ts
- packages/conform-valibot/tests/coercion/schema/objectWithRestAsync.test.ts
- packages/conform-valibot/tests/coercion/schema/strictObject.test.ts
- packages/conform-valibot/tests/coercion/schema/strictObjectAsync.test.ts
Valibot has also been modified to support validation of forms with nested checkboxes only, just like zod.
references: https://github.com/edmundhung/conform/pull/733
Zod has a `zodDiscriminatedUnion` schema, but valibot does not. Therefore, the same support as https://github.com/edmundhung/conform/pull/909 will not be performed.
> fix(conform-valibot): support nested fields with only checkboxes

- .changeset/kind-coats-lie.md
- packages/conform-valibot/coercion.ts
- packages/conform-valibot/tests/coercion/schema/array.test.ts
- packages/conform-valibot/tests/coercion/schema/nullish.test.ts
- packages/conform-valibot/tests/coercion/schema/nullishAsync.test.ts
- packages/conform-valibot/tests/coercion/schema/optional.test.ts
- packages/conform-valibot/tests/coercion/schema/optionalAsync.test.ts
- packages/conform-valibot/tests/coercion/schema/union.test.ts
Close #916 
The following validation should succeed:
```ts
import { object, nullish, array, number } from 'valibot';
import { parseWithValibot } from '@conform-to/valibot';
const schema = object({
age: nullish(array(number())),
});
expect(parseWithValibot(new FormData(), { schema })).toMatchObject({
status: 'success',
value: {},
});
```
However, the above validation does not pass because `@conform-to/valitob` uses `transform` to convert empty strings as follows:
```ts
import * as v from 'valibot';
const Schema = v.object({
ticketSpecs: v.pipe(
// The `unknown` schema makes it seem as though the `ticketSpecs` value must have some value.
v.unknown(),
v.transform(v => typeof v !== 'string' ? v : (v === '' ? undefined : v)),
v.nullish(
v.array(
v.number()
),
[]),
)
});
const result = …
```
> fix: where `undefined` value could not be correctly verified when `array` was defined in `nullish` or `optional` schema

- .eslintignore
- .github/workflows/tests.yml
- .prettierignore
- packages/conform-dom/.gitignore
- packages/conform-dom/rollup.config.js
- packages/conform-react/.gitignore
- packages/conform-react/rollup.config.js
- packages/conform-valibot/.gitignore
- packages/conform-valibot/rollup.config.js
- packages/conform-validitystate/.gitignore
- packages/conform-validitystate/rollup.config.js
- packages/conform-yup/.gitignore
- packages/conform-yup/rollup.config.js
- packages/conform-zod/.gitignore
- packages/conform-zod/rollup.config.js
We were copying the `README` file over to each package before publishing it. But it fails silently when we renamed it to `README.md`. This should fix the issue 😓
> chore: ensure readme is copied during build

- .changeset/config.json
- .changeset/thirty-eyes-sell.md
As discussed in https://github.com/edmundhung/conform/pull/911#issuecomment-2831917866, this should trigger changesets to bump the `@conform-to/valibot` package version to `1.5.0` and sync it with the rest of the packages going forward.
> chore: sync @conform-to/valibot package version

- .changeset/smooth-shrimps-sell.md
- packages/conform-zod/coercion.ts
- tests/conform-zod.spec.ts
(partially) resolves #928 
This allows `z.literal` for number, boolean, and bigint types to coerce input to their respective values.
Previously, you had to write something like:
```ts
z.boolean().refine(v => v === true)
z.boolean().pipe(z.literal(true))
z.number().refine(v => v === 0)
z.number().pipe(z.literal(0))
```
Now, you can simply write:
```ts
z.literal(true)
z.literal(0)
```
> feat(conform-zod): Add support auto type coercion with z.literal for boolean, number, and bigint

- .changeset/tasty-planes-arrive.md
- packages/conform-valibot/coercion.ts
- packages/conform-valibot/tests/coercion/schema/literal.test.ts
https://github.com/edmundhung/conform/pull/930
Zod now supports numbers, booleans, and BigInt values ​​for literals, so we'll fix it so that valibot supports them as well.
> feat(conform-valibot): Add support auto type coercion with z.literal for boolean, number, and bigint

- .changeset/grumpy-starfishes-invent.md
- packages/conform-zod/v4/coercion.ts
- pnpm-lock.yaml
Close #944 
Zod changed the internal property used by `discriminatedUnion` from version 3.25.35 onwards. As a result, schema validation using `discriminatedUnion` will not work properly in Zod versions 3.25.35 and later. Fixed so that it works properly in versions 3.25.35 and later.
https://github.com/colinhacks/zod/commit/fe75806cbb64683f237ed0e4ee93b67a2c5e976d
However, this is a workaround fix. I would like to use a process that does not actually need to access this internal property.
> fix(conform-zod): `discriminatedUnion` schema to work properly in Zod versions 3.25.35 and later

- .changeset/spotty-mails-sleep.md
- docs/api/react/getFieldsetProps.md
- docs/api/react/getFormProps.md
- docs/ja/api/react/getFieldsetProps.md
- docs/ja/api/react/getFormProps.md
- docs/ja/tutorial.md
- docs/tutorial.md
- packages/conform-react/helpers.ts
- tests/conform-react.spec.ts
- tests/integrations/input-attributes.spec.ts
Removes aria-invalid from getFormProps and getFieldsetProps. This change matches [the applicable roles for aria-invalid](https://w3c.github.io/aria/#aria-invalid).
Note: I do not know Japanese so I'm not sure if the changes to the Japanese docs are grammatically correct
Fixes #955
> fix(conform-react): Remove aria-invalid from form and fieldset

- .changeset/wise-dragons-develop.md
- packages/conform-zod/v4/coercion.ts
- packages/conform-zod/v4/tests/coercion/schema/discriminatedUnion.test.ts
Close #968
Fixed a bug where a schema combining `discriminatedUnion` could not be validated correctly.
Zod v4 allows you to define a schema combining `discriminatedUnion`.
https://zod.dev/v4?id=upgraded-zdiscriminatedunion
> fix(conform-zod): coercion for composed discriminated unions

- .changeset/clean-eggs-try.md
- docs/api/zod/future/coerceFormValue.md
- docs/api/zod/future/formatResult.md
- docs/api/zod/future/memoize.md
- guide/app/layout.tsx
- packages/conform-zod/memoize.ts
- packages/conform-zod/package.json
- packages/conform-zod/rollup.config.js
- packages/conform-zod/tests/memoize.test.ts
- packages/conform-zod/v3/coercion.ts
- packages/conform-zod/v3/format.ts
- packages/conform-zod/v3/future.ts
- packages/conform-zod/v3/tests/format.test.ts
- packages/conform-zod/v4/format.ts
- packages/conform-zod/v4/future.ts
- packages/conform-zod/v4/tests/format.test.ts
This PR adds `formatResult` and `memoize` helpers to future exports:
- **`formatResult`**: Transforms Zod validation results into Conform's error format, supporting value extraction and custom error formatting
- **`memoize`**: Caches most recent result to prevent redundant API calls during async validation
Both helpers are available in `@conform-to/zod/v3/future` and `@conform-to/zod/v4/future`
> feat(conform-zod): add formatResult and memoize helpers

- docs/api/react/future/FormProvider.md
- docs/api/react/future/useForm.md
- docs/api/react/future/useFormMetadata.md
- guide/app/layout.tsx
This is pretty much copied from the v1 FormProvider docs, except using future APIs in the example.
> docs: add FormProvider details

- .changeset/gold-geese-cough.md
- docs/api/react/future/useField.md
- docs/api/react/future/useFormMetadata.md
- packages/conform-react/future/state.ts
- packages/conform-react/future/types.ts
- packages/conform-react/tests/state.test.ts
- packages/conform-react/tests/useField.browser.test.tsx
- packages/conform-react/tests/useFormMetadata.browser.test.tsx
Fix https://github.com/edmundhung/conform/discussions/1014#discussioncomment-14355524
This restores form and field metadata that were present in v1 but accidentally omitted from the future `useForm` hook release:
- Add `key`, `errorId` and `descriptionId` properties to form metadata
- Add `valid` property to both form and field metadata with `invalid` deprecated and to be removed in 1.10.0
- Add `formId` property to field metadata  
- Add `fieldErrors` to field metadata (renamed from v1's `allErrors`) with improvements:
- Keys use relative paths scoped to the parent field instead of full field names
- Excludes the current field's own errors (only includes child field errors)
> fix(conform-react): restore missing v1 metadata in future useForm hook

- .changeset/flat-balloons-tap.md
- packages/conform-react/future/hooks.tsx
- packages/conform-react/future/state.ts
- packages/conform-react/tests/useForm.node.test.tsx
Fix #1030
Close #1035
This is originally submitted in #1035 by @apostolos, but I can't push any changes to it as it is made from the default branch of a fork.
> fix(conform-react/future): use static reset key for initial form state

- guide/app/components.tsx
- guide/app/layout.tsx
i fixed some layout stuff that kept bugging me about the docs.
mainly the content would crash into the logo on initial load.
> docs: small layout fixes

- packages/conform-zod/v3/coercion.ts
- packages/conform-zod/v3/tests/coercion/schema/default.test.ts
Fix #1049
I am a little bit confused what is the right behavior here. As Zod 3 seems to validate against the default value, but zod 4 doesn't 🤔 
I also can't find anything related in Zod's migration docs: https://zod.dev/v4/changelog#default-updates
cc: @chimame
> fix(conform-zod/v3): zod default schema behavior when coercion is enabled
